blogapp/urls.py
from django.urls import path
from blogapp import views

urlpatterns = [
    path("accounts/signup",views.SignUpView.as_view(),name="signup"),
    path("accounts/signin",views.LoginView.as_view(),name="login"),
    path("home",views.IndexView.as_view(),name="home"),
    path("users/profile/add",views.CreateUserProfileView.as_view(),name="add-profile"),
    path("users/profile/view",views.ViewMyprofileView.as_view(),name="view-profile"),
    path("accounts/signout",views.sign_out,name="signout"),
    path("users/password/change",views.PasswordResetView.as_view(),name="password-reset"),
    path("user/profile/change/<int:user_id>",views.ProfileUpdateView.as_view(),name="profile-update"),
    path("user/propic/edit/<int:user_id>",views.ChangeProfilePicView.as_view(),name="pic-change"),
    path("post/comment/<int:post_id>",views.add_comment,name="add-comment"),
    path("post/like/add/<int:post_id>",views.add_like,name="add-like"),
    path("users/follow/add/<int:user_id>",views.follow_friend,name="follow-frnd"),

]

socialapplication/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/",include("blogapp.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
import random

# Create your models here.

class UserProfile(models.Model):
    profile_picture=models.ImageField(upload_to="profilepics",null=True)
    bio=models.CharField(max_length=20)
    phone=models.CharField(max_length=15)
    date_of_birth=models.DateField(null=True)
    options=(
        ("male","male"),
        ("female","female"),
        ("other","other")
    )
    gender=models.CharField(max_length=15,choices=options,default="male")
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="users")
    following=models.ManyToManyField(User,related_name="followings",blank=True)


    @property
    def fetch_followings(self):
        return self.following.all()

    @property
    def fetch_following_count(self):
        return self.fetch_followings.count()

    @property
    def get_followers(self):
        all_users=UserProfile.objects.all()
        followers_list=[]
        for user in all_users:
            if self.user in user.fetch_followings:
                followers_list.append(user)
        return followers_list

    @property
    def followers_count(self):
        return len(self.get_followers)


    @property
    def get_invitations(self):
        all_users_profile = UserProfile.objects.all().exclude(user=self.user)# fetch all users profile objects except current or loged user
        # taking user objects from all_users_profile
        user_list=[userprofile.user for userprofile in all_users_profile]
        following_list = [u for u in self.fetch_followings]  # exclude my following from all users
        invitations = [user for user in user_list if user not in following_list]
        return invitations
        # return random.sample(invitations,1)

class Blogs(models.Model):
    title=models.CharField(max_length=150)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to="blogimages",null=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name="author")
    posted_date=models.DateTimeField(auto_now_add=True)
    liked_by=models.ManyToManyField(User)

    @property
    def get_like_count(self):
        like_count=self.liked_by.all().count()
        return like_count
    @property
    def get_liked_users(self):
        liked_users=self.liked_by.all()
        users=[user.username for user in liked_users]
        return users

    def __str__(self):
        return self.title


class Comments(models.Model):
    blog=models.ForeignKey(Blogs,on_delete=models.CASCADE)
    comment=models.CharField(max_length=190)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

blogapp/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm

from django.contrib.auth.forms import UserCreationForm
from django import forms
from blogapp.models import UserProfile,Blogs,Comments

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=[
            "first_name","last_name","username","email","password1","password2"
        ]


class LoginForm(forms.Form):
        username=forms.CharField()
        password=forms.CharField()


class UserProfileForm(ModelForm):
    class Meta:
        model=UserProfile
        exclude=("user","following",)
        widgets={
            "date_of_birth":forms.DateInput(attrs={"class":"form-control","type":"date"})
        }

class PasswordResetForm(forms.Form):
    old_password=forms.CharField(widget=forms.PasswordInput)
    new_password=forms.CharField(widget=forms.PasswordInput)
    confirm_password=forms.CharField()

class BlogForm(ModelForm):
    class Meta:
        model=Blogs
        fields=["title","description","image"]
        widgets={
            "title":forms.TextInput(attrs={"class":"form-control"}),
            "description":forms.Textarea(attrs={"class":"form-control"}),
            "image":forms.FileInput(attrs={"class":"form-control"})

        }
class ChangePropicForm(ModelForm):
    class Meta:
        model=UserProfile
        fields=["profile_picture"]
        widgets={
            "profile_picture":forms.FileInput(attrs={"class":"form-control"})
        }

class CommentForm(ModelForm):
    class Meta:
        model=Comments
        fields=["comment"]
        widgets={
            "comment":forms.TextInput(attrs={"class":"form-control","placeholder":"add comment"})
        }

blogapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from blogapp.forms import UserRegistrationForm, LoginForm, UserProfileForm, PasswordResetForm, BlogForm,ChangePropicForm,CommentForm
from django.views.generic import View, CreateView, FormView, TemplateView, UpdateView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from blogapp.models import UserProfile, Blogs,Comments
from django.utils.decorators import method_decorator


# Create your views here.


def signin_required(fn):
    def wrapper(request,*args,**kwargs):
        if request.user.is_authenticated:
            return fn(request,*args,**kwargs)
        else:
            messages.error(request,"user must login")
            return redirect("login")
    return wrapper




class SignUpView(CreateView):
    form_class = UserRegistrationForm
    template_name = "reg.html"
    model = User
    success_url = reverse_lazy("login")

    # def get(self,request,*args,**kwargs):
    #     form=self.form_class()
    #     return render(request,self.template_name,{"form":form})
    # def post(self,request,*args,**kwargs):
    #     form=self.form_class(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         messages.success(request, "registration successful")
    #         return redirect("signup")
    #     else:
    #         messages.error(request, "registration failed")
    #         return render(request,self.template_name,{"form":form})


class LoginView(FormView):
    form_class = LoginForm
    template_name = "login.html"
    model = User

    # def get(self,request,*args,**kwargs):
    #     form=self.form_class()
    #     return render(request,self.template_name,{"form":form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            uname = form.cleaned_data.get("username")
            pswd = form.cleaned_data.get("password")
            user = authenticate(request, username=uname, password=pswd)
            if user:
                login(request, user)
                print("success")
                return redirect("home")
            else:
                messages.error(request, "Invalid Credentials")
                return render(request, self.template_name, {"form": form})
        return render(request, self.template_name, {"form": form})

@method_decorator(signin_required,name="dispatch")
class IndexView(CreateView):
    model = Blogs
    form_class = BlogForm
    success_url = reverse_lazy("home")
    template_name = "home1.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        self.object = form.save()
        messages.success(self.request, "Post has been saved")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blg = Blogs.objects.all().order_by("-posted_date")
        context["blogs"] = blg
        comment_form=CommentForm()
        context["comment_form"]=comment_form
        return context

@method_decorator(signin_required,name="dispatch")
class CreateUserProfileView(CreateView):
    model = UserProfile
    template_name = "addprofile.html"
    form_class = UserProfileForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "Profile has been Added")
        self.object = form.save()
        return super().form_valid(form)

@method_decorator(signin_required,name="dispatch")
class ViewMyprofileView(TemplateView):
    template_name = "view-profile.html"

@signin_required
def sign_out(request, *args, **kwargs):
    logout(request)
    return redirect("login")

@method_decorator(signin_required,name="dispatch")
class PasswordResetView(FormView):
    template_name = "passwordreset.html"
    form_class = PasswordResetForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            oldpassword = form.cleaned_data.get("old_password")
            psw1 = form.cleaned_data.get("new_password")
            psw2 = form.cleaned_data.get("confirm_password")
            user = authenticate(request, username=request.user.username, password=oldpassword)
            if user:
                user.set_password(psw2)
                user.save()
                messages.success(request, "Password Changed")
                return redirect("login")
            else:
                messages.error(request, "Invalid Credentials")
                return render(request, self.template_name, {"form": form})

@method_decorator(signin_required,name="dispatch")
class ProfileUpdateView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = "profileupdate.html"
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"

    def form_valid(self, form):
        messages.success(self.request, "Profile has been Updated")
        self.object = form.save()
        return super().form_valid(form)

@method_decorator(signin_required,name="dispatch")
class ChangeProfilePicView(UpdateView):
    template_name = "change-propic.html"
    form_class = ChangePropicForm
    model=UserProfile
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"

    def form_valid(self, form):
        messages.success(self.request, "Profile has been Updated")
        self.object = form.save()
        return super().form_valid(form)


@signin_required
def add_comment(request,*args,**kwargs):
    if request.method=="POST":
        blog_id=kwargs.get("post_id")
        blog=Blogs.objects.get(id=blog_id)
        user=request.user
        comment=request.POST.get("comment")
        Comments.objects.create(blog=blog,comment=comment,user=user)
        messages.success(request,"Comment has been posted")
        return redirect("home")


@signin_required
def add_like(request,*args,**kwargs):
    blog_id=kwargs.get("post_id")
    blog=Blogs.objects.get(id=blog_id)
    blog.liked_by.add(request.user)
    blog.save()
    return redirect("home")


@signin_required
def follow_friend(request,*args,**kwargs):
    friend_id=kwargs.get("user_id")
    friend_profile=User.objects.get(id=friend_id)
    request.user.users.following.add(friend_profile)
    friend_profile.save()
    messages.success(request,"your started following  "+friend_profile.username)
    return redirect("home")

blogapp/templates/b1.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-danger sticky-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{%static 'images/social.png'%}" alt="" style="width:60px;margin-left:60px"></a>
            <h2>My<span>Blog</span></h2>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#" >Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{%url 'add-profile'%}">Add Profile</a></li>
                  <li><a class="dropdown-item" href="#">Change Password</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
<!--              <li class="nav-item">-->
<!--                <a class="nav-link disabled">Disabled</a>-->
<!--              </li>-->
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>



<body>
<div class="container">
 {%block body_block%}

  {%endblock%}
</div>
</body>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>

blogapp/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href="./style.css"> -->
    <script src="https://kit.fontawesome.com/23846bd33a.js" crossorigin="anonymous"></script>
    <!-- CSS only -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- style css -->
    <style>
     @import url('https://fonts.googleapis.com/css2?family=Babylonica&family=Boogaloo&family=Caveat&family=Cookie&family=Dancing+Script&family=Ingrid+Darling&family=Lavishly+Yours&family=Lobster+Two&family=Macondo&family=Meie+Script&family=MonteCarlo&family=My+Soul&family=Oleo+Script&family=Pacifico&family=Satisfy&family=Source+Serif+Pro:wght@200&family=Tapestry&family=Ultra&family=Updock&family=Yellowtail&display=swap');

          *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    /* background-image: url(./images/blg.jpg); */
    background-size: cover;
    background-position: center;
    font-family: sans-serif;
}
.menu-bar{
    background: rgb(229, 73, 73);
    text-align: center;
    height: 85px;
}
.menu-bar ul{
    display:inline-flex;
    list-style: none;
    color: white;

}
.menu-bar ul li{
    width: 120px;
    margin: 15px;
    padding: 15px;
}
.menu-bar ul li a{
    text-decoration: none;
    color: white;
     font-family: 'Tapestry', cursive;

}
.active, .menu-bar ul li:hover
{
    /* background:rgb(244, 68, 68);
    border-radius: 3px; */
    color:rgb(243, 233, 232)
}
.sub-menu{
    display: none;
}
.menu-bar ul li:hover .sub-menu{
    display: block;
    position: absolute;
    background-color: rgb(229, 73, 73);
    margin-top: 15px;
    margin-left: -15px;
}
.menu-bar ul li:hover .sub-menu ul{
    display: block;
    margin: 10px;

}
.menu-bar ul li:hover .sub-menu ul li{
    width: 90px;
    padding: 3px;
    border-bottom: 1px  double #fff;
    background: transparent;
    border-radius: 0;
    text-align: left;

}
.menu-bar ul li:hover .sub-menu ul li:last-child{
    border-bottom: none;
}
.menu-bar ul li:hover .sub-menu ul li a:hover{
    color: #5d0303;
}

input[type="search"]{
    border: none;
    position:absolute;
    left: 77%;
    top: 21%;
    border-radius: 9px;
    padding: 10px;
    outline: none;
}
#sb{
    position:absolute;
    margin-left: 588px;
    margin-top: 32px;
    
}
.sc1{
    height: 60px;
    width: 60px;
    margin-top: 14px;
    margin-left: 629px;
    border-radius:50%;
    cursor:pointer;
}
.card{
    border-radius: 24px;
    background-color: #FFF;
    width: 320px;
}
.card-image{
    position: relative;
    height: 150px;
    width: 150px;
    border-radius: 50%;
    background: rgb(251, 249, 249);
    padding: 3px;
}
.card-image .card-img{
    height: 100%;
    width: 100%;
    object-fit: cover;
    border-radius: 50%;
    border: 4px solid rgb(255, 131, 131);
}
.image-content, .card-content{
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 10px 14px;

}
.image-content{
    row-gap: 5px;
    position: relative;
    
}
.name{
    font-size: 18px;
    font-weight: 500px;
    color: #863e0a;
}
.description{
    font-size: 14px;
    color: #333;
    text-align: center;
}
.button{
    border: none;
    font-size: 16px;
    color: #fff;
    padding: 8px 16px;
    background-color: rgb(244, 88, 82);
    border-radius: 6px;
    margin: 14px;
    cursor: pointer;
    transition: all 0.3s ease;
    text-decoration:none;
}
.button:hover{
    background: #fff;
    color: rgb(244, 88, 82);


}

.overlay{
    position: absolute;
    left:0;
    top: 0;
    height: 57%;
    width: 100%;
    background-color: rgb(245, 95, 95);
    border-radius: -6px 25px 0 25px;

}
.card-body{
    text-align: center;
}
.mbl{
    text-align: center;
    margin-top: 30px;
    font-family: 'Ultra', serif;
}
span{
  color: #df2b2b;
}





    </style>


    <!--  -->
</head>
<body>
<div class="menu-bar sticky-top">
    <ul>
        <!--        {%if request.user.users.profile_picture%}-->
        <!--      <a href="{%url 'pic-change' request.user.users.id%}" class="n1">-->
        <!--            <img src="{{request.user.users.profile_picture.url}}" alt="" class="sc1"></a>-->
        <!--        {%endif%}-->
        <li class="active"><a href="{%url 'home'%}">Home </a></li>
        <li><a href="#">Link </a></li>
        <li><a href="#">Profile </a><i class="fa fa-angle-down"></i>
            <div class="sub-menu">
                <ul>
                    {%if request.user.users%}
                    <!--                    <li><a href="{%url 'view-profile'%}"></a></li>-->
                    {%else%}
                    <li><a href="{%url 'add-profile'%}">Add Profile</a></li>
                    {%endif%}
                    <li><a href="{%url 'password-reset'%}">Change Password</a></li>
                    <li><a href="#">update</a></li>
                    <li><a href="#">View</a></li>
                </ul>
            </div>
        </li>
        <li><a href="#">About Us </a></li>
        <li><a href="{%url 'signout'%}">Logout</a></li>
        <form action="" method="get">
            <input type="search" placeholder="search here" required="required"><i class="fa-solid fa-magnifying-glass"
                                                                                  id="sb"></i>
        </form>
        {%if request.user.users.profile_picture%}
        <a href="{%url 'pic-change' request.user.users.id%}" class="n1">
            <img src="{{request.user.users.profile_picture.url}}" alt="" class="sc1"></a>
        {%endif%}
    </ul>

</div>
<h1 class="mbl">My<span>Blog</span></h1>
<div class="container" style="margin-top: 100px; margin-left: 40px; position:sticky">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="image-content">
                    <span class="overlay"></span>
                    <div class="card-image">
                        {%if request.user.users.profile_picture%}
                        <img src="{{request.user.users.profile_picture.url}}" alt="" class="card-img">
                        {%else%}
                        <img src="{%static 'images/propic.jpg'%}" alt="" class="card-img">
                        {%endif%}
                    </div>
                </div>
                <div class="card-content">
                    <h2 class="name"><i class="fa fa-user" style="color:red"></i>{{request.user}}</h2>
                    <p class="description"></p>

                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><i class="fa-solid fa-blog" style="color:red"></i>{{request.user.users.bio}}
                    </li>
                    <li class="list-group-item"><i class="fa fa-phone" style="color:red"></i>{{request.user.users.phone}}
                    </li>
                    <li class="list-group-item"><i class="fa-solid fa-cake-candles" style="color:red"></i>{{request.user.users.date_of_birth}}
                    </li>
                </ul>
                <div class="card-body">
                    {%if request.user.users%}
                    <a href="{%url 'profile-update' request.user.users.id%}" class="button">UpdateProfile</a>
                    {%endif%}

                </div>

            </div>
            <hr>

            <!-- <h1>hello</h1> -->

            <div class="container border border-danger"
                 style="width:70%;height:12%;margin-left:20px;border-radius:15px">
                <h4 style="color:red">followings</h4>
                {%for user in request.user.users.fetch_followings%}
                <h6>{{user}}</h6>
                {%endfor%}
                <h4 >Count</h4>
               <h4 style="color:#d11313">{{request.user.users.fetch_following_count}}</h4>
                <hr>
                <h4>followers</h4>
                {%for user in request.user.users.get_followers%}
                    {{user.user}}
                {%endfor%}
<!--                                {{request.user.users.get_followers}}-->
                <h4>Count</h4>
                {{request.user.users.followers_count}}


            </div>
            <br>
            <h4 style="margin-left:20px">Suggestions</h4>
            {%if request.user.users.get_invitations%}
            {%for user in request.user.users.get_invitations%}
            <br>

            <div class="card m-1 mt-3" style="width:20rem;height:191px">
                <img class="card-img-top" src="{{user.users.profile_picture.url}}" alt=""
                     style="height: 80px;width: 80px;margin-top: 18px;margin-left:15px;border-radius: 50%;cursor: pointer;">
                <div class="card-body">
                    <h5 class="card-title" style="margin-top:-70px;margin-left:-12px">{{user.username}}</h5><br>
                    <hr>
                    <a href="{%url 'follow-frnd' user.id%}" class="button">Follow</a>
                </div>
            </div>
            {%endfor%}
            {%endif%}


        </div>


        <div class="col-8">

            <body>
            <div class="container">
                {%if messages%}
                {%for msg in messages%}


                {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>HEY!</strong> {{msg}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                <!--            <div class="bg-info text-dark">-->
                <!--                {{msg}}-->
                <!--            </div>-->
                {%endif%}
                {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>HEY!</strong>{{msg}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                <!--            <div class="bg-danger text-white">-->
                <!--                {{msg}}-->
                <!--            </div>-->
                {%endif%}
                {%endfor%}
                {%endif%}
            </div>
            {%block body_block%}

            {%endblock%}
        </div>
</body>
</div>


</div>
</div>
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/23846bd33a.js" crossorigin="anonymous"></script>
</html>

blogapp/templates/home.html
{%extends 'base1.html'%}
{%block body_block%}
<!--<div class="container">-->

<!--{%load static%}-->
<!--<link rel="stylesheet" href="{%static 'css/style.css'%}">-->

<!--</style>-->
  <div class="row">

    <div class="col-4"></div>
    <div class="col-4">
      <h1 class="mt-5"style="text-align:center">WELCOME{{request.user}}</h1>
    </div>
    <div class="col-4"></div>
  </div>

<div class="row">
<!--  <div class="col-4"></div>-->
  <div class="col-7">
    <div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style="color:red;background-color:light">
        Add Post
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
         <form action="" method="post" enctype="multipart/form-data">
            {%csrf_token%}
<!--              {{form.as_p}}-->
           <label>Title</label>
           <input type="text" class="form-control" name="title" id="id_title" placeholder="Title"><br>
           <label>Description</label>
            <input type="text" class="form-control" name="description" id="id_description"
                           placeholder="Description"><br>
           <label>Upload image</label>
           <input type="file" class="form-control" name="image" id="id_image" placeholder="Upload Image"><br>
      <input type="submit" value="post" class="btn btn-danger" style="margin-left:50%">
    </form>

      </div>
    </div>
  </div>
<!--    <form action="" method="post" enctype="multipart/form-data">-->
<!--            {%csrf_token%}-->
<!--              {{form.as_p}}-->
<!--      <input type="submit" value="post" class="btn btn-danger" style="margin-left:50%">-->
<!--    </form>-->
  </div>
  <div class="col-4"></div>
</div>
{%for blog in blogs%}
<!--  demo-->
<div class="container border border-danger mt-5" style="border-radius: 6px;padding: 20px;color: #626262;margin: 20px 0; width:100%;align-items:center;">
  <div class="col-4"></div>
  <div class="col-4">
    <p>{{blog.title}}</p>
    {%if blog.image%}
      <img src="{{blog.image.url}}" class="img-fluid" alt="..." style="width: 100%;border-radius: 4px;margin-bottom: 5px;">
    <p>Posted_by :{{blog.author}}</p>
    <p>Created_at :{{blog.posted_date}}</p>
    <a href="{%url 'add-like' blog.id%}"><i class="fa-solid fa-thumbs-up" style="font-size:169%"></i></a>
        {{blog.get_like_count}}
<!--        {{blog.get_liked_users}}-->
    {%for name in blog.get_liked_users%}
    {{name}}
    {%endfor%}
    <form action="{%url 'add-comment' blog.id%}" method="post">
      {%csrf_token%}
      {{comment_form.as_p}}
      {%for comment in blog.comments_set.all%}
      <div>
       <h6> {{comment.comment}}</h6>
       <h6>Commented by: {{comment.user}}</h6>
      </div>
      {%endfor%}
      <input type="submit" class="btn btn-danger">
    </form>
    {%endif%}
  </div>
  <div class="col-4"></div>
</div>
<!--</div>-->
{%endfor%}

{%endblock%}

blogapp/templates/view-profile.html
{%extends 'base.html'%}
{%block body_block%}

{{request.user.users.bio}}
{{request.user.users.date_of_birth}}
{{request.user.users.phone}}
{%endblock%}